use a global replace to join multiple line Vensim equations in comments
climateinteractive/SDEverywhere pull request #175
Opened 2022-03-19 04:38 UTC by ToddFincannon

See #174.

2022-03-21 19:23 UTC, chrispcampbell requested changes
@ToddFincannon: The fix looks harmless, but could you please add a test case for this?  I tried quickly adding one myself but wasn't able to reproduce since I wasn't sure which part of that example equation is triggering the issue.  (Like, is it the length of the entire equation, or the multiple backslash continuations, or a combination?)

2022-03-31 22:28 UTC, ToddFincannon commented
@chrispcampbell: I didn't include a test case because I believed the change to be simple enough that it was not required. Any input with a single newline will give the same result that we had before. I tried extracting the long equation from EPS that triggered this bug, but it pulled in so many other things, that it would take a long time to get a valid equation. I can say that this change fixed the EPS problem in situ. I prefer not to take the effort to construct another test case.

2022-04-04 19:22 UTC, chrispcampbell commented
@ToddFincannon: OK, understood.  I just wanted to make sure we have an independent test case on hand for changes like this to ensure coverage for refactoring work I'd like to get to someday.  I was able to build an isolated test case (see `longeqns`, included in this branch) using the EPS equation you included in the issue.  The names weren't important, just the structure (and line break locations) of the equation, so it ended up being pretty quick to add.  I'll merge this PR shortly.

2022-04-04 19:22 UTC, merged

2022-04-04 19:24 UTC, chrispcampbell approved these changes